# Generated by Django 5.0.1 on 2024-01-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price_alter_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bathroom',
            field=models.IntegerField(default=1),
        ),
    ]
