# Generated by Django 5.0.1 on 2024-01-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_firstname_architect_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
